// Generated by https://quicktype.io

export interface ScapeGeItem {
    item: Item;
}

export interface Item {
    icon:        string;
    icon_large:  string;
    id:          number;
    type:        string;
    typeIcon:    string;
    name:        string;
    description: string;
    current:     Current;
    today:       Current;
    members:     string;
    day30:       Day;
    day90:       Day;
    day180:      Day;
}

export interface Current {
    trend: string;
    price: string;
}

export interface Day {
    trend:  string;
    change: string;
}
